In [43]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

In [44]:
dataset = pd.read_csv('./data/Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [45]:
x[0:10, :]

array([[619, 'France', 'Female', 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 'Female', 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 'Female', 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 'Female', 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 'Female', 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 'Male', 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 'Male', 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 'Female', 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 'Male', 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 'Male', 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [46]:
labelEncoder = LabelEncoder()
x[:, 2] = labelEncoder.fit_transform(x[:, 2])

In [47]:
x[0:10, :]

array([[619, 'France', 0, 42, 2, 0.0, 1, 1, 1, 101348.88],
       [608, 'Spain', 0, 41, 1, 83807.86, 1, 0, 1, 112542.58],
       [502, 'France', 0, 42, 8, 159660.8, 3, 1, 0, 113931.57],
       [699, 'France', 0, 39, 1, 0.0, 2, 0, 0, 93826.63],
       [850, 'Spain', 0, 43, 2, 125510.82, 1, 1, 1, 79084.1],
       [645, 'Spain', 1, 44, 8, 113755.78, 2, 1, 0, 149756.71],
       [822, 'France', 1, 50, 7, 0.0, 2, 1, 1, 10062.8],
       [376, 'Germany', 0, 29, 4, 115046.74, 4, 1, 0, 119346.88],
       [501, 'France', 1, 44, 4, 142051.07, 2, 0, 1, 74940.5],
       [684, 'France', 1, 27, 2, 134603.88, 1, 1, 1, 71725.73]],
      dtype=object)

In [ ]:
column_transformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])],
                                       remainder='passthrough')
x = np.array(column_transformer.fit_transform(x))

In [20]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [21]:
standrad_scale = StandardScaler()
x_train = standrad_scale.fit_transform(x_train)
x_test = standrad_scale.transform(x_test)

## Building de ANN

In [22]:
ann = tf.keras.models.Sequential()

In [23]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [24]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [25]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Training the ANN

In [26]:
ann.compile(optimizer='adam',
            loss='binary_crossentropy',
            metrics=['accuracy'])

In [27]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 698us/step - accuracy: 0.7362 - loss: 0.6043
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 701us/step - accuracy: 0.7995 - loss: 0.4740
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - accuracy: 0.8081 - loss: 0.4472
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - accuracy: 0.8081 - loss: 0.4377
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - accuracy: 0.8111 - loss: 0.4302
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 691us/step - accuracy: 0.8156 - loss: 0.4228
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 689us/step - accuracy: 0.8184 - loss: 0.4151
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 738us/step - accuracy: 0.8234 - loss: 0.4065
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - accuracy: 0.8267 - loss: 0.3971
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 695us/step - accuracy: 0.8273 - loss: 0.3880
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 697us/step - accuracy: 0.8279 - loss: 0.3811
Epoch 12/100
250/25

## Predictions & Evaluations

In [31]:
ann.predict(standrad_scale.transform([[1, 0, 0,
                                       600, 1, 40,
                                       3, 60000, 2,
                                       1, 1, 50000]]) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[0.01316948]], dtype=float32)

In [36]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step


In [37]:
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1516   79]
 [ 192  213]]


0.8645